### ISSUE TITLE
Pan/zoom does not work on mobile Android

### ISSUE THREAD

**Issue by mnordine** [aurimasg/blaze#3]
Doesn't work in Chrome or FF.

**Comment by aurimasg** [comment]
Made gesture recognition fixes in 4347a5c4477d796a8bd067d7490bac2e02c9eaf2 and f90ea1598fec133bf578df8ea63d3f6923fed2b3.

New binaries uploaded to https://gasiulis.name/parallel-rasterization-on-cpu/demo/.

It should work better on wider range on devices now.
